import { useEffect, useRef } from 'react';
import { supabase } from '@/components/utils/supabaseClient';

// Well-known test keys — safe for dev.
// Replace with real keys generated by: npx web-push generate-vapid-keys
// Add VITE_VAPID_PUBLIC_KEY to Vercel environment variables for production.
const VAPID_PUBLIC_KEY =
  import.meta.env.VITE_VAPID_PUBLIC_KEY ||
  'BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjZEcx6Kf5MuoXMjbWjia4K22AvXQ';

function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  return Uint8Array.from([...rawData].map((c) => c.charCodeAt(0)));
}

/**
 * usePushNotifications (auto-setup)
 *
 * Registers the service worker, requests notification permission, subscribes
 * to the Push API, and stores the subscription in Supabase for future
 * server-side push delivery. Called once from OSArchitecture — no UI needed.
 *
 * Fails silently: the push_subscriptions table may not exist until the
 * migration (20260226000095_push_subscriptions.sql) is applied.
 */
export function usePushNotifications(): void {
  const subscribed = useRef(false);

  useEffect(() => {
    if (subscribed.current) return;
    if (!('serviceWorker' in navigator) || !('PushManager' in window)) return;

    const setup = async () => {
      try {
        const reg = await navigator.serviceWorker.register('/sw.js');
        const permission = await Notification.requestPermission();
        if (permission !== 'granted') return;

        const existing = await reg.pushManager.getSubscription();
        const sub =
          existing ||
          (await reg.pushManager.subscribe({
            userVisibleOnly: true,
            applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY) as BufferSource,
          }));

        // Store subscription in Supabase so a future server-side push function
        // can deliver messages even when the tab is closed.
        try {
          const {
            data: { user },
          } = await supabase.auth.getUser();
          if (user) {
            await supabase
              .from('push_subscriptions')
              .upsert(
                {
                  user_id: user.id,
                  subscription: JSON.stringify(sub),
                  updated_at: new Date().toISOString(),
                },
                { onConflict: 'user_id' }
              )
              .select();
          }
        } catch (dbErr) {
          // Table may not exist yet — non-fatal
          console.warn('[Push] push_subscriptions upsert skipped:', dbErr);
        }

        subscribed.current = true;
      } catch (e) {
        // Push setup failed silently — non-critical
        console.warn('[Push] Push setup failed:', e);
      }
    };

    setup();
  }, []);
}

export default usePushNotifications;
