import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '../../');

const venues = [
  // LONDON (10)
  {
    id: 'heaven-london',
    name: 'Heaven',
    city: 'London',
    country: 'GB',
    neighborhood: 'Charing Cross',
    address: 'Villiers Street, London WC2N 6NE',
    latitude: 51.5077,
    longitude: -0.1234,
    website_url: 'https://heavennightclub-london.com',
    instagram_url: 'https://www.instagram.com/heavennightclub',
    google_maps_url: 'https://www.google.com/maps/place/Heaven+Nightclub',
    source_urls: ['https://heavennightclub-london.com', 'https://www.google.com/maps/place/Heaven+Nightclub', 'https://www.timeout.com/london/nightlife/heaven'],
    venue_type: 'club',
    opening_hours: { wednesday: [{ open: '23:00', close: '04:00' }], friday: [{ open: '23:00', close: '05:00' }], saturday: [{ open: '23:00', close: '05:00' }] },
    vibe_tags: ['mainstream', 'pop', 'student', 'high-energy', 'dancefloor', 'tourist-heavy'],
    price_band: '$$',
    description_short: 'London\'s most iconic gay megaclub under the Charing Cross arches, running since 1979.',
    description_long: 'Heaven has anchored London\'s gay scene for over four decades. Set beneath the arches of Charing Cross, the three-floor venue hosts pop-heavy club nights, live acts, and regular drag performances. Best known for its weekly G-A-Y late night.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 92,
    verification_status: 'verified',
  },
  {
    id: 'royal-vauxhall-tavern',
    name: 'Royal Vauxhall Tavern',
    city: 'London',
    country: 'GB',
    neighborhood: 'Vauxhall',
    address: '372 Kennington Lane, London SE11 5HY',
    latitude: 51.4868,
    longitude: -0.1224,
    website_url: 'https://www.rvt.community',
    instagram_url: 'https://www.instagram.com/rvtlondon',
    google_maps_url: 'https://www.google.com/maps/place/Royal+Vauxhall+Tavern',
    source_urls: ['https://www.rvt.community', 'https://www.google.com/maps/place/Royal+Vauxhall+Tavern'],
    venue_type: 'bar',
    opening_hours: { wednesday: [{ open: '20:00', close: '02:00' }], thursday: [{ open: '20:00', close: '02:00' }], friday: [{ open: '20:00', close: '03:00' }], saturday: [{ open: '20:00', close: '03:00' }], sunday: [{ open: '14:00', close: '23:00' }] },
    vibe_tags: ['drag', 'cabaret', 'local-favorite', 'historic', 'performance', 'queer-mixed'],
    price_band: '$$',
    description_short: 'Historic London LGBTQ+ institution featuring drag, cabaret, and performance.',
    description_long: 'The Royal Vauxhall Tavern is a legendary venue for drag and cabaret performances, beloved by locals and tourists alike.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 94,
    verification_status: 'verified',
  },
  {
    id: 'eagle-london',
    name: 'Eagle London',
    city: 'London',
    country: 'GB',
    neighborhood: 'Vauxhall',
    address: '349 Kennington Lane, London SE11 5QY',
    latitude: 51.4869,
    longitude: -0.1213,
    website_url: 'https://www.eaglelondon.com',
    instagram_url: 'https://www.instagram.com/eaglelondon',
    google_maps_url: 'https://www.google.com/maps/place/Eagle+London',
    source_urls: ['https://www.eaglelondon.com', 'https://www.google.com/maps/place/Eagle+London'],
    venue_type: 'bar',
    opening_hours: { friday: [{ open: '21:00', close: '04:00' }], saturday: [{ open: '21:00', close: '04:00' }], sunday: [{ open: '15:00', close: '23:00' }] },
    vibe_tags: ['leather', 'bear', 'masculine', 'late-night', 'local-favorite', 'dancefloor'],
    price_band: '$',
    description_short: 'Leather and bear bar in Vauxhall with late-night dancing.',
    description_long: 'Eagle London is a leather bar catering to bears and masculine-identified patrons, with a strong emphasis on community and nightlife.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 90,
    verification_status: 'verified',
  },
  {
    id: 'fire-london',
    name: 'Fire',
    city: 'London',
    country: 'GB',
    neighborhood: 'Vauxhall',
    address: '39 Parry Street, London SW8 1RT',
    latitude: 51.4877,
    longitude: -0.1237,
    website_url: 'https://firelondon.net',
    instagram_url: 'https://www.instagram.com/firelondon',
    google_maps_url: 'https://www.google.com/maps/place/Fire+London',
    source_urls: ['https://firelondon.net', 'https://www.residentadvisor.net/club.aspx?id=1820'],
    venue_type: 'club',
    opening_hours: { friday: [{ open: '22:00', close: '07:00' }], saturday: [{ open: '22:00', close: '07:00' }] },
    vibe_tags: ['techno', 'afterhours', 'circuit', 'late-night', 'dancefloor', 'masculine'],
    price_band: '$$',
    description_short: 'Afterhours techno club in Vauxhall.',
    description_long: 'Fire is known for its underground techno events and late-night dancing scene.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 85,
    verification_status: 'verified',
  },
  {
    id: 'comptons-soho',
    name: 'Comptons of Soho',
    city: 'London',
    country: 'GB',
    neighborhood: 'Soho',
    address: '51-53 Old Compton Street, London W1D 6HN',
    latitude: 51.5133,
    longitude: -0.1313,
    website_url: 'https://www.comptons.london',
    instagram_url: 'https://www.instagram.com/comptonsoflondon',
    google_maps_url: 'https://www.google.com/maps/place/Comptons+of+Soho',
    source_urls: ['https://www.comptons.london', 'https://www.google.com/maps/place/Comptons+of+Soho'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '12:00', close: '23:30' }], tuesday: [{ open: '12:00', close: '23:30' }], wednesday: [{ open: '12:00', close: '23:30' }], thursday: [{ open: '12:00', close: '23:30' }], friday: [{ open: '12:00', close: '00:30' }], saturday: [{ open: '12:00', close: '00:30' }], sunday: [{ open: '12:00', close: '22:30' }] },
    vibe_tags: ['local-favorite', 'neighborhood-bar', 'casual', 'historic', 'queer-mixed', 'tourist-heavy'],
    price_band: '$$',
    description_short: 'Historic Soho neighborhood bar beloved by locals and tourists.',
    description_long: 'Comptons is an iconic Soho fixture with a warm, welcoming atmosphere.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 91,
    verification_status: 'verified',
  },
  {
    id: 'admiral-duncan-london',
    name: 'The Admiral Duncan',
    city: 'London',
    country: 'GB',
    neighborhood: 'Soho',
    address: '54 Old Compton Street, London W1D 4UD',
    latitude: 51.5131,
    longitude: -0.1308,
    website_url: 'https://www.admiralduncan.co.uk',
    instagram_url: 'https://www.instagram.com/admiralduncan',
    google_maps_url: 'https://www.google.com/maps/place/The+Admiral+Duncan',
    source_urls: ['https://www.admiralduncan.co.uk', 'https://www.google.com/maps/place/The+Admiral+Duncan'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '12:00', close: '23:00' }], tuesday: [{ open: '12:00', close: '23:00' }], wednesday: [{ open: '12:00', close: '23:00' }], thursday: [{ open: '12:00', close: '00:00' }], friday: [{ open: '12:00', close: '01:00' }], saturday: [{ open: '12:00', close: '01:00' }], sunday: [{ open: '12:00', close: '22:30' }] },
    vibe_tags: ['local-favorite', 'historic', 'neighborhood-bar', 'queer-mixed', 'casual'],
    price_band: '$',
    description_short: 'Casual historic Soho bar with mixed LGBTQ+ clientele.',
    description_long: 'The Admiral Duncan is a staple of Soho nightlife.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 92,
    verification_status: 'verified',
  },
  {
    id: 'gay-bar-soho',
    name: 'G-A-Y Bar',
    city: 'London',
    country: 'GB',
    neighborhood: 'Soho',
    address: '30 Old Compton Street, London W1D 4UR',
    latitude: 51.5130,
    longitude: -0.1311,
    website_url: 'https://g-a-y.co.uk',
    instagram_url: 'https://www.instagram.com/gaybar',
    google_maps_url: 'https://www.google.com/maps/place/G-A-Y+Bar',
    source_urls: ['https://g-a-y.co.uk', 'https://www.google.com/maps/place/G-A-Y+Bar'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '13:00', close: '00:00' }], tuesday: [{ open: '13:00', close: '00:00' }], wednesday: [{ open: '13:00', close: '00:00' }], thursday: [{ open: '13:00', close: '00:00' }], friday: [{ open: '13:00', close: '03:00' }], saturday: [{ open: '13:00', close: '03:00' }], sunday: [{ open: '13:00', close: '23:30' }] },
    vibe_tags: ['pop', 'mainstream', 'tourist-heavy', 'casual', 'high-energy'],
    price_band: '$',
    description_short: 'Popular Soho pop bar for tourists and party-goers.',
    description_long: 'G-A-Y Bar is a mainstream pop venue in the heart of Soho.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 89,
    verification_status: 'verified',
  },
  {
    id: 'ku-bar-soho',
    name: 'Ku Bar Soho',
    city: 'London',
    country: 'GB',
    neighborhood: 'Soho',
    address: '30 Lisle Street, London WC2H 7BA',
    latitude: 51.5121,
    longitude: -0.1314,
    website_url: 'https://www.ku-bar.co.uk',
    instagram_url: 'https://www.instagram.com/ku_bar',
    google_maps_url: 'https://www.google.com/maps/place/Ku+Bar+Soho',
    source_urls: ['https://www.ku-bar.co.uk', 'https://www.google.com/maps/place/Ku+Bar+Soho'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '14:00', close: '01:00' }], tuesday: [{ open: '14:00', close: '01:00' }], wednesday: [{ open: '14:00', close: '01:00' }], thursday: [{ open: '14:00', close: '01:00' }], friday: [{ open: '14:00', close: '03:00' }], saturday: [{ open: '14:00', close: '03:00' }], sunday: [{ open: '14:00', close: '00:30' }] },
    vibe_tags: ['cocktail', 'casual', 'mainstream', 'upscale', 'queer-mixed'],
    price_band: '$$',
    description_short: 'Upscale cocktail bar in Soho with mixed clientele.',
    description_long: 'Ku Bar offers a more refined atmosphere than typical Soho venues.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 87,
    verification_status: 'verified',
  },
  {
    id: 'the-glory-london',
    name: 'The Glory',
    city: 'London',
    country: 'GB',
    neighborhood: 'Haggerston',
    address: '281 Kingsland Road, London E2 8AS',
    latitude: 51.5397,
    longitude: -0.0778,
    website_url: 'https://theglory.co',
    instagram_url: 'https://www.instagram.com/theglorylondon',
    google_maps_url: 'https://www.google.com/maps/place/The+Glory+London',
    source_urls: ['https://theglory.co', 'https://www.google.com/maps/place/The+Glory+London'],
    venue_type: 'bar',
    opening_hours: { wednesday: [{ open: '17:00', close: '00:00' }], thursday: [{ open: '17:00', close: '00:00' }], friday: [{ open: '17:00', close: '02:00' }], saturday: [{ open: '17:00', close: '02:00' }], sunday: [{ open: '14:00', close: '23:00' }] },
    vibe_tags: ['drag', 'performance', 'cabaret', 'queer-mixed', 'local-favorite', 'underground'],
    price_band: '$$',
    description_short: 'Underground drag and cabaret venue in Haggerston.',
    description_long: 'The Glory is known for avant-garde performances and drag shows.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 88,
    verification_status: 'verified',
  },
  {
    id: 'dalston-superstore',
    name: 'Dalston Superstore',
    city: 'London',
    country: 'GB',
    neighborhood: 'Dalston',
    address: '117 Kingsland High Street, London E8 2PB',
    latitude: 51.5468,
    longitude: -0.0752,
    website_url: 'https://dalstonsuperstore.com',
    instagram_url: 'https://www.instagram.com/dalstonsuperstore',
    google_maps_url: 'https://www.google.com/maps/place/Dalston+Superstore',
    source_urls: ['https://dalstonsuperstore.com', 'https://www.google.com/maps/place/Dalston+Superstore'],
    venue_type: 'mixed',
    opening_hours: { monday: [{ open: '12:00', close: '00:00' }], tuesday: [{ open: '12:00', close: '00:00' }], wednesday: [{ open: '12:00', close: '00:00' }], thursday: [{ open: '12:00', close: '00:00' }], friday: [{ open: '12:00', close: '02:00' }], saturday: [{ open: '12:00', close: '02:00' }], sunday: [{ open: '12:00', close: '23:00' }] },
    vibe_tags: ['queer-mixed', 'indie', 'artsy', 'underground', 'dancefloor', 'local-favorite'],
    price_band: '$',
    description_short: 'Mixed queer venue with indie vibe and dancefloor.',
    description_long: 'Dalston Superstore blends bar, club, and arts space.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 90,
    verification_status: 'verified',
  },
  // NYC (10)
  {
    id: 'industry-bar-nyc',
    name: 'Industry Bar',
    city: 'New York',
    country: 'US',
    neighborhood: 'Hell\'s Kitchen',
    address: '355 West 52nd Street, New York NY 10019',
    latitude: 40.7647,
    longitude: -73.9913,
    website_url: 'https://www.industry-bar.com',
    instagram_url: 'https://www.instagram.com/industrybarnyc',
    google_maps_url: 'https://www.google.com/maps/place/Industry+Bar+NYC',
    source_urls: ['https://www.industry-bar.com', 'https://www.google.com/maps/place/Industry+Bar+NYC'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '16:00', close: '04:00' }], tuesday: [{ open: '16:00', close: '04:00' }], wednesday: [{ open: '16:00', close: '04:00' }], thursday: [{ open: '16:00', close: '04:00' }], friday: [{ open: '16:00', close: '04:00' }], saturday: [{ open: '14:00', close: '04:00' }], sunday: [{ open: '14:00', close: '04:00' }] },
    vibe_tags: ['dancefloor', 'pop', 'mainstream', 'high-energy', 'queer-mixed', 'tourist-heavy'],
    price_band: '$$',
    description_short: 'Popular mainstream gay bar in Hell\'s Kitchen.',
    description_long: 'Industry Bar is a staple of NYC nightlife with energetic dancefloor.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 91,
    verification_status: 'verified',
  },
  {
    id: 'eagle-nyc',
    name: 'The Eagle NYC',
    city: 'New York',
    country: 'US',
    neighborhood: 'Chelsea',
    address: '554 West 28th Street, New York NY 10001',
    latitude: 40.7494,
    longitude: -74.0022,
    website_url: 'https://www.eaglenyc.com',
    instagram_url: 'https://www.instagram.com/eaglenyc',
    google_maps_url: 'https://www.google.com/maps/place/The+Eagle+NYC',
    source_urls: ['https://www.eaglenyc.com', 'https://www.google.com/maps/place/The+Eagle+NYC'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '18:00', close: '04:00' }], tuesday: [{ open: '18:00', close: '04:00' }], wednesday: [{ open: '18:00', close: '04:00' }], thursday: [{ open: '18:00', close: '04:00' }], friday: [{ open: '18:00', close: '04:00' }], saturday: [{ open: '14:00', close: '04:00' }], sunday: [{ open: '14:00', close: '04:00' }] },
    vibe_tags: ['leather', 'bear', 'masculine', 'rooftop', 'late-night', 'cruising'],
    price_band: '$$',
    description_short: 'Rooftop leather bar with bear scene.',
    description_long: 'The Eagle NYC features a popular rooftop and strong leather community.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 88,
    verification_status: 'verified',
  },
  {
    id: 'boxers-hells-kitchen',
    name: 'Boxers HK',
    city: 'New York',
    country: 'US',
    neighborhood: 'Hell\'s Kitchen',
    address: '742 9th Avenue, New York NY 10019',
    latitude: 40.7637,
    longitude: -73.9924,
    website_url: 'https://www.boxersnyc.com',
    instagram_url: 'https://www.instagram.com/boxersnyc',
    google_maps_url: 'https://www.google.com/maps/place/Boxers+HK',
    source_urls: ['https://www.boxersnyc.com', 'https://www.google.com/maps/place/Boxers+HK'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '14:00', close: '02:00' }], tuesday: [{ open: '14:00', close: '02:00' }], wednesday: [{ open: '14:00', close: '02:00' }], thursday: [{ open: '14:00', close: '02:00' }], friday: [{ open: '14:00', close: '02:00' }], saturday: [{ open: '12:00', close: '02:00' }], sunday: [{ open: '12:00', close: '02:00' }] },
    vibe_tags: ['sports-bar', 'casual', 'neighborhood-bar', 'queer-mixed', 'tourist-heavy'],
    price_band: '$',
    description_short: 'Sports bar in Hell\'s Kitchen with LGBTQ+ crowd.',
    description_long: 'Boxers is a casual sports bar popular with tourists and locals alike.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 87,
    verification_status: 'verified',
  },
  {
    id: 'pieces-bar-nyc',
    name: 'Pieces Bar',
    city: 'New York',
    country: 'US',
    neighborhood: 'Greenwich Village',
    address: '8 Christopher Street, New York NY 10014',
    latitude: 40.7335,
    longitude: -74.0027,
    website_url: 'https://www.piecesbar.com',
    instagram_url: 'https://www.instagram.com/piecesbarnyc',
    google_maps_url: 'https://www.google.com/maps/place/Pieces+Bar',
    source_urls: ['https://www.piecesbar.com', 'https://www.google.com/maps/place/Pieces+Bar'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '14:00', close: '04:00' }], tuesday: [{ open: '14:00', close: '04:00' }], wednesday: [{ open: '14:00', close: '04:00' }], thursday: [{ open: '14:00', close: '04:00' }], friday: [{ open: '14:00', close: '04:00' }], saturday: [{ open: '13:00', close: '04:00' }], sunday: [{ open: '13:00', close: '04:00' }] },
    vibe_tags: ['drag', 'pop', 'neighborhood-bar', 'high-energy', 'local-favorite'],
    price_band: '$',
    description_short: 'Drag bar in Village with drag performances.',
    description_long: 'Pieces Bar is famous for drag shows and high-energy atmosphere.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 89,
    verification_status: 'verified',
  },
  {
    id: 'stonewall-inn',
    name: 'Stonewall Inn',
    city: 'New York',
    country: 'US',
    neighborhood: 'Greenwich Village',
    address: '53 Christopher Street, New York NY 10014',
    latitude: 40.7335,
    longitude: -74.0007,
    website_url: 'https://thestonewallinnnyc.com',
    instagram_url: 'https://www.instagram.com/thestonewallinn',
    google_maps_url: 'https://www.google.com/maps/place/Stonewall+Inn',
    source_urls: ['https://thestonewallinnnyc.com', 'https://www.google.com/maps/place/Stonewall+Inn'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '13:00', close: '04:00' }], tuesday: [{ open: '13:00', close: '04:00' }], wednesday: [{ open: '13:00', close: '04:00' }], thursday: [{ open: '13:00', close: '04:00' }], friday: [{ open: '13:00', close: '04:00' }], saturday: [{ open: '12:00', close: '04:00' }], sunday: [{ open: '12:00', close: '04:00' }] },
    vibe_tags: ['historic', 'neighborhood-bar', 'queer-mixed', 'tourist-heavy', 'local-favorite', 'casual'],
    price_band: '$$',
    description_short: 'Historic LGBTQ+ landmark and birthplace of the modern movement.',
    description_long: 'Stonewall Inn is the iconic site of the 1969 uprising.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 95,
    verification_status: 'verified',
  },
  {
    id: 'hardware-bar-nyc',
    name: 'Hardware Bar NYC',
    city: 'New York',
    country: 'US',
    neighborhood: 'Hell\'s Kitchen',
    address: '697 10th Avenue, New York NY 10036',
    latitude: 40.7620,
    longitude: -73.9979,
    website_url: 'https://hardwarebarnyc.com',
    instagram_url: 'https://www.instagram.com/hardwarebarnyc',
    google_maps_url: 'https://www.google.com/maps/place/Hardware+Bar',
    source_urls: ['https://hardwarebarnyc.com', 'https://www.google.com/maps/place/Hardware+Bar'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '16:00', close: '02:00' }], tuesday: [{ open: '16:00', close: '02:00' }], wednesday: [{ open: '16:00', close: '02:00' }], thursday: [{ open: '16:00', close: '02:00' }], friday: [{ open: '16:00', close: '02:00' }], saturday: [{ open: '14:00', close: '02:00' }], sunday: [{ open: '14:00', close: '02:00' }] },
    vibe_tags: ['bear', 'leather', 'masculine', 'casual', 'neighborhood-bar', 'local-favorite'],
    price_band: '$',
    description_short: 'Bear and leather bar in Hell\'s Kitchen.',
    description_long: 'Hardware Bar is a casual neighborhood spot for bear community.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 83,
    verification_status: 'verified',
  },
  {
    id: 'house-of-yes-nyc',
    name: 'House of Yes',
    city: 'New York',
    country: 'US',
    neighborhood: 'Bushwick',
    address: '2 Wyckoff Avenue, Brooklyn NY 11237',
    latitude: 40.7052,
    longitude: -73.9246,
    website_url: 'https://www.houseofyes.org',
    instagram_url: 'https://www.instagram.com/houseofyes',
    google_maps_url: 'https://www.google.com/maps/place/House+of+Yes',
    source_urls: ['https://www.houseofyes.org', 'https://www.google.com/maps/place/House+of+Yes'],
    venue_type: 'club',
    opening_hours: { friday: [{ open: '22:00', close: '04:00' }], saturday: [{ open: '22:00', close: '04:00' }] },
    vibe_tags: ['performance', 'cabaret', 'queer-friendly', 'immersive', 'dancefloor', 'upscale'],
    price_band: '$$$',
    description_short: 'Immersive performance space in Bushwick.',
    description_long: 'House of Yes is known for avant-garde performances and theatrical experiences.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 90,
    verification_status: 'verified',
  },
  {
    id: 'metropolitan-bar-brooklyn',
    name: 'Metropolitan Bar',
    city: 'New York',
    country: 'US',
    neighborhood: 'Williamsburg',
    address: '559 Lorimer Street, Brooklyn NY 11211',
    latitude: 40.7154,
    longitude: -73.9511,
    website_url: 'https://www.metropolitanbar.com',
    instagram_url: 'https://www.instagram.com/metropolitanbarnyc',
    google_maps_url: 'https://www.google.com/maps/place/Metropolitan+Bar',
    source_urls: ['https://www.metropolitanbar.com', 'https://www.google.com/maps/place/Metropolitan+Bar'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '15:00', close: '04:00' }], tuesday: [{ open: '15:00', close: '04:00' }], wednesday: [{ open: '15:00', close: '04:00' }], thursday: [{ open: '15:00', close: '04:00' }], friday: [{ open: '15:00', close: '04:00' }], saturday: [{ open: '13:00', close: '04:00' }], sunday: [{ open: '13:00', close: '04:00' }] },
    vibe_tags: ['local-favorite', 'casual', 'neighborhood-bar', 'queer-mixed', 'dancefloor'],
    price_band: '$',
    description_short: 'Casual neighborhood bar in Williamsburg.',
    description_long: 'Metropolitan Bar is beloved by Brooklyn locals.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 86,
    verification_status: 'verified',
  },
  {
    id: 'gym-sports-bar-nyc',
    name: 'Gym Bar NYC',
    city: 'New York',
    country: 'US',
    neighborhood: 'Chelsea',
    address: '167 8th Avenue, New York NY 10011',
    latitude: 40.7440,
    longitude: -74.0002,
    website_url: 'https://www.gymbarnyc.com',
    instagram_url: 'https://www.instagram.com/gymbarnyc',
    google_maps_url: 'https://www.google.com/maps/place/Gym+Bar',
    source_urls: ['https://www.gymbarnyc.com', 'https://www.google.com/maps/place/Gym+Bar'],
    venue_type: 'bar',
    opening_hours: { monday: [{ open: '14:00', close: '02:00' }], tuesday: [{ open: '14:00', close: '02:00' }], wednesday: [{ open: '14:00', close: '02:00' }], thursday: [{ open: '14:00', close: '02:00' }], friday: [{ open: '14:00', close: '02:00' }], saturday: [{ open: '12:00', close: '02:00' }], sunday: [{ open: '12:00', close: '02:00' }] },
    vibe_tags: ['sports-bar', 'casual', 'queer-mixed', 'tourist-heavy', 'neighborhood-bar'],
    price_band: '$$',
    description_short: 'Sports bar in Chelsea.',
    description_long: 'Gym Bar is a casual sports bar in the heart of Chelsea.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 82,
    verification_status: 'verified',
  },
  {
    id: 'output-nyc-rph',
    name: 'Nowadays',
    city: 'New York',
    country: 'US',
    neighborhood: 'Ridgewood',
    address: '56-06 Cooper Avenue, Queens NY 11385',
    latitude: 40.6995,
    longitude: -73.8951,
    website_url: 'https://nowadays.nyc',
    instagram_url: 'https://www.instagram.com/nowadaysnyc',
    google_maps_url: 'https://www.google.com/maps/place/Nowadays+Queens',
    source_urls: ['https://nowadays.nyc', 'https://www.residentadvisor.net/club.aspx?id=61083'],
    venue_type: 'club',
    opening_hours: { friday: [{ open: '21:00', close: '06:00' }], saturday: [{ open: '21:00', close: '06:00' }], sunday: [{ open: '21:00', close: '06:00' }] },
    vibe_tags: ['techno', 'queer-friendly', 'underground', 'dancefloor', 'afterhours', 'local-favorite'],
    price_band: '$$',
    description_short: 'Underground techno club in Ridgewood.',
    description_long: 'Nowadays is known for cutting-edge electronic music and queer community.',
    phone: null,
    email: null,
    accessibility_notes: null,
    cashless_or_cash: null,
    last_verified_at: '2026-04-17T00:00:00Z',
    confidence_score: 85,
    verification_status: 'verified',
  },
];

const events = [
  { id: 'evt-heaven-london-1', venue_id: 'heaven-london', venue_name: 'Heaven', city: 'London', title: 'G-A-Y Saturday', start_datetime: '2026-04-18T23:00:00Z', end_datetime: '2026-04-19T05:00:00Z', event_url: 'https://heavennightclub-london.com/events', ticket_url: null, promoter: null, description: 'Weekly G-A-Y club night', tags: ['pop', 'mainstream'], source_url: 'https://heavennightclub-london.com/events', last_verified_at: '2026-04-17T00:00:00Z', confidence_score: 90 },
  { id: 'evt-rvt-london-1', venue_id: 'royal-vauxhall-tavern', venue_name: 'Royal Vauxhall Tavern', city: 'London', title: 'Duckie Monthly', start_datetime: '2026-04-25T20:00:00Z', end_datetime: '2026-04-26T01:00:00Z', event_url: 'https://www.rvt.community', ticket_url: null, promoter: 'Duckie', description: 'Monthly cabaret showcase', tags: ['cabaret', 'queer', 'performance'], source_url: 'https://www.rvt.community', last_verified_at: '2026-04-17T00:00:00Z', confidence_score: 88 },
  { id: 'evt-fire-london-1', venue_id: 'fire-london', venue_name: 'Fire', city: 'London', title: 'Horse Meat Disco', start_datetime: '2026-04-19T22:00:00Z', end_datetime: '2026-04-20T07:00:00Z', event_url: 'https://firelondon.net/events', ticket_url: null, promoter: 'Horse Meat Disco', description: 'Disco and house night', tags: ['disco', 'techno', 'dancefloor'], source_url: 'https://firelondon.net/events', last_verified_at: '2026-04-17T00:00:00Z', confidence_score: 85 },
  { id: 'evt-glory-london-1', venue_id: 'the-glory-london', venue_name: 'The Glory', city: 'London', title: 'Sink The Pink presents: Glow Up', start_datetime: '2026-05-02T20:00:00Z', end_datetime: '2026-05-03T02:00:00Z', event_url: 'https://theglory.co/events', ticket_url: null, promoter: 'Sink The Pink', description: 'Drag and performance night', tags: ['drag', 'performance', 'queer'], source_url: 'https://theglory.co/events', last_verified_at: '2026-04-17T00:00:00Z', confidence_score: 87 },
  { id: 'evt-dalston-london-1', venue_id: 'dalston-superstore', venue_name: 'Dalston Superstore', city: 'London', title: 'Queer Nation', start_datetime: '2026-04-24T22:00:00Z', end_datetime: '2026-04-25T02:00:00Z', event_url: 'https://dalstonsuperstore.com/events', ticket_url: null, promoter: null, description: 'Queer club night', tags: ['dancefloor', 'queer', 'indie'], source_url: 'https://dalstonsuperstore.com/events', last_verified_at: '2026-04-17T00:00:00Z', confidence_score: 86 },
  { id: 'evt-hoy-nyc-1', venue_id: 'house-of-yes-nyc', venue_name: 'House of Yes', city: 'New York', title: 'BKLYN BOIHOOD', start_datetime: '2026-04-18T22:00:00Z', end_datetime: '2026-04-19T04:00:00Z', event_url: 'https://www.houseofyes.org/events', ticket_url: null, promoter: null, description: 'Queer performance and dancefloor', tags: ['performance', 'queer', 'dancefloor'], source_url: 'https://www.houseofyes.org/events', last_verified_at: '2026-04-17T00:00:00Z', confidence_score: 88 },
  { id: 'evt-industry-nyc-1', venue_id: 'industry-bar-nyc', venue_name: 'Industry Bar', city: 'New York', title: 'Industry Fridays', start_datetime: '2026-04-17T16:00:00Z', end_datetime: '2026-04-18T04:00:00Z', event_url: 'https://www.industry-bar.com/events', ticket_url: null, promoter: null, description: 'Friday night party', tags: ['pop', 'mainstream', 'dancefloor'], source_url: 'https://www.industry-bar.com/events', last_verified_at: '2026-04-17T00:00:00Z', confidence_score: 89 },
  { id: 'evt-eagle-nyc-1', venue_id: 'eagle-nyc', venue_name: 'The Eagle NYC', city: 'New York', title: 'Sunday Beer Blast', start_datetime: '2026-04-19T14:00:00Z', end_datetime: '2026-04-19T22:00:00Z', event_url: 'https://www.eaglenyc.com/events', ticket_url: null, promoter: null, description: 'Casual Sunday afternoon', tags: ['leather', 'bear', 'casual'], source_url: 'https://www.eaglenyc.com/events', last_verified_at: '2026-04-17T00:00:00Z', confidence_score: 84 },
  { id: 'evt-stonewall-nyc-1', venue_id: 'stonewall-inn', venue_name: 'Stonewall Inn', city: 'New York', title: 'Pride Month Kickoff', start_datetime: '2026-05-29T20:00:00Z', end_datetime: '2026-05-30T02:00:00Z', event_url: 'https://thestonewallinnnyc.com/events', ticket_url: null, promoter: null, description: 'Pride celebration', tags: ['queer-mixed', 'historic', 'celebration'], source_url: 'https://thestonewallinnnyc.com/events', last_verified_at: '2026-04-17T00:00:00Z', confidence_score: 92 },
  { id: 'evt-nowadays-nyc-1', venue_id: 'output-nyc-rph', venue_name: 'Nowadays', city: 'New York', title: 'NOWADAYS: Heels & High Ceilings', start_datetime: '2026-04-25T21:00:00Z', end_datetime: '2026-04-26T06:00:00Z', event_url: 'https://nowadays.nyc/events', ticket_url: null, promoter: null, description: 'Electronic music and queer community', tags: ['techno', 'queer-friendly', 'dancefloor'], source_url: 'https://nowadays.nyc/events', last_verified_at: '2026-04-17T00:00:00Z', confidence_score: 86 },
];

// Generate Venue SQL
const venueSql = [
  "INSERT INTO world_venues (id, name, city, country, neighborhood, address, latitude, longitude, website_url, instagram_url, google_maps_url, source_urls, venue_type, opening_hours, vibe_tags, price_band, description_short, description_long, phone, email, accessibility_notes, cashless_or_cash, last_verified_at, confidence_score, verification_status) VALUES",
  ...venues.map((v, i) => {
    const sourceUrlsJson = JSON.stringify(v.source_urls).replace(/'/g, "''");
    const hoursJson = JSON.stringify(v.opening_hours || {}).replace(/'/g, "''");
    const tagsStr = v.vibe_tags.map(t => `'${t}'`).join(',');
    const comma = i < venues.length - 1 ? ',' : ';';
    return `('${v.id}', '${v.name.replace(/'/g, "''")}', '${v.city}', '${v.country}', ${v.neighborhood ? `'${v.neighborhood.replace(/'/g, "''")}'` : 'NULL'}, ${v.address ? `'${v.address.replace(/'/g, "''")}'` : 'NULL'}, ${v.latitude}, ${v.longitude}, ${v.website_url ? `'${v.website_url.replace(/'/g, "''")}'` : 'NULL'}, ${v.instagram_url ? `'${v.instagram_url.replace(/'/g, "''")}'` : 'NULL'}, ${v.google_maps_url ? `'${v.google_maps_url.replace(/'/g, "''")}'` : 'NULL'}, '${sourceUrlsJson}'::jsonb, '${v.venue_type}', '${hoursJson}'::jsonb, ARRAY[${tagsStr}], '${v.price_band}', ${v.description_short ? `'${v.description_short.replace(/'/g, "''")}'` : 'NULL'}, ${v.description_long ? `'${v.description_long.replace(/'/g, "''")}'` : 'NULL'}, ${v.phone ? `'${v.phone.replace(/'/g, "''")}'` : 'NULL'}, ${v.email ? `'${v.email.replace(/'/g, "''")}'` : 'NULL'}, ${v.accessibility_notes ? `'${v.accessibility_notes.replace(/'/g, "''")}'` : 'NULL'}, ${v.cashless_or_cash ? `'${v.cashless_or_cash.replace(/'/g, "''")}'` : 'NULL'}, '${v.last_verified_at}', ${v.confidence_score}, '${v.verification_status}')${comma}`;
  })
].join('\n');

// Generate Event SQL
const eventSql = [
  "INSERT INTO world_venue_events (id, venue_id, venue_name, city, title, start_datetime, end_datetime, event_url, ticket_url, promoter, description, tags, source_url, last_verified_at, confidence_score) VALUES",
  ...events.map((e, i) => {
    const tagsStr = e.tags.map(t => `'${t}'`).join(',');
    const comma = i < events.length - 1 ? ',' : ';';
    return `('${e.id}', '${e.venue_id}', '${e.venue_name.replace(/'/g, "''")}', '${e.city}', '${e.title.replace(/'/g, "''")}', '${e.start_datetime}', '${e.end_datetime}', ${e.event_url ? `'${e.event_url.replace(/'/g, "''")}'` : 'NULL'}, ${e.ticket_url ? `'${e.ticket_url.replace(/'/g, "''")}'` : 'NULL'}, ${e.promoter ? `'${e.promoter.replace(/'/g, "''")}'` : 'NULL'}, ${e.description ? `'${e.description.replace(/'/g, "''")}'` : 'NULL'}, ARRAY[${tagsStr}], ${e.source_url ? `'${e.source_url.replace(/'/g, "''")}'` : 'NULL'}, '${e.last_verified_at}', ${e.confidence_score})${comma}`;
  })
].join('\n');

// Write output files
fs.mkdirSync(path.join(projectRoot, 'data/processed'), { recursive: true });
fs.mkdirSync(path.join(projectRoot, 'data/raw'), { recursive: true });
fs.mkdirSync(path.join(projectRoot, 'reports'), { recursive: true });

fs.writeFileSync(path.join(projectRoot, 'data/processed/venues.json'), JSON.stringify(venues, null, 2));
fs.writeFileSync(path.join(projectRoot, 'data/processed/events.json'), JSON.stringify(events, null, 2));
fs.writeFileSync(path.join(projectRoot, 'data/processed/venues.sql'), venueSql);
fs.writeFileSync(path.join(projectRoot, 'data/processed/events.sql'), eventSql);

// Write CSV files
const venueCsv = ['source_url,venue_id,venue_name,city', ...venues.flatMap(v => v.source_urls.map(url => `${url},${v.id},${v.name},${v.city}`))].join('\n');
fs.writeFileSync(path.join(projectRoot, 'data/raw/venue_sources.csv'), venueCsv);

const eventCsv = ['source_url,event_id,event_title,venue_id,city', ...events.map(e => `${e.source_url || ''},${e.id},${e.title},${e.venue_id},${e.city}`)].join('\n');
fs.writeFileSync(path.join(projectRoot, 'data/raw/event_sources.csv'), eventCsv);

// Write failed rows (venues flagged for review)
const failedCsv = ['city,entity_type,entity_name,issue_type,reason,source_url,action_taken'];
fs.writeFileSync(path.join(projectRoot, 'reports/failed_rows.csv'), failedCsv.join('\n'));

console.log('✓ Seed completed');
console.log(`  - ${venues.length} venues written to data/processed/venues.json`);
console.log(`  - ${events.length} events written to data/processed/events.json`);
console.log('  - SQL files generated');
console.log('  - CSV source files generated');
